name: e_vendas
description: Projeto e_vendas com Flutter Modular e MobX
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  mobx: ^2.3.0
  flutter_mobx: ^2.0.6+5
  dio: ^5.8.0+1
  dart_jsonwebtoken: ^2.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  mobx_codegen: ^2.3.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo_white.png
    - assets/images/logo_complete.png
    - assets/images/logo_name_city.png