name: e_vendas
description: "Projeto Flutter para vendas de planos odontológicos (e-Vendas)"
publish_to: 'none' # Mantém privado, remova para publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Ícones estilo iOS
  cupertino_icons: ^1.0.8

  # Navegação e injeção de dependências
  flutter_modular: ^6.3.4

  # MobX para gerenciamento de estado
  mobx: ^2.2.1
  flutter_mobx: ^2.3.0

  # Requisições HTTP
  dio: ^5.4.0
  shared_preferences: ^2.5.3
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.2
  qr_flutter: ^4.1.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  msix: ^3.16.12
  wakelock_plus: ^1.4.0
  flutter_svg: ^2.2.0
  webview_flutter: ^4.13.0
  webview_flutter_android: ^4.10.0
  webview_flutter_wkwebview: ^3.23.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de código para MobX
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.1

  # Lints recomendadas do Flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_complete.png
    - assets/images/logo_white.png
    - assets/images/logo_somoscoop_verde.svg

msix_config:
  display_name: E-Vendas
  publisher_display_name: Uniodonto Goiânia
  identity_name: com.uniodonto.evendas
  msix_version: 1.0.0.0
  logo_path: assets/windows_logo.png